/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(auth)'}/setup` | `/setup`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/theme-context`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SuccessToast`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/foodIcons`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/activities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TipsModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/cats` | `/cats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/food` | `/food`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `${'/(auth)'}/setup` | `/setup`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/theme-context`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/SuccessToast`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/foodIcons`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/recommendations`; params?: Router.UnknownOutputParams; } | { pathname: `/../lib/activities`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/TipsModal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/cats` | `/cats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/food` | `/food`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/stats` | `/stats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `${'/(auth)'}/setup${`?${string}` | `#${string}` | ''}` | `/setup${`?${string}` | `#${string}` | ''}` | `/../lib/theme-context${`?${string}` | `#${string}` | ''}` | `/../components/SuccessToast${`?${string}` | `#${string}` | ''}` | `/../lib/foodIcons${`?${string}` | `#${string}` | ''}` | `/../lib/recommendations${`?${string}` | `#${string}` | ''}` | `/../lib/activities${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `/../components/TipsModal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/cats${`?${string}` | `#${string}` | ''}` | `/cats${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/food${`?${string}` | `#${string}` | ''}` | `/food${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/stats${`?${string}` | `#${string}` | ''}` | `/stats${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `${'/(auth)'}/setup` | `/setup`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/theme-context`; params?: Router.UnknownInputParams; } | { pathname: `/../components/SuccessToast`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/foodIcons`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/recommendations`; params?: Router.UnknownInputParams; } | { pathname: `/../lib/activities`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `/../components/TipsModal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/cats` | `/cats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/food` | `/food`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/stats` | `/stats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; };
    }
  }
}
